apiVersion: v1
kind: Service
metadata:
  name: microventa-service
  labels:
    name: microventa-service
    app: microservice
spec:
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30010
  selector:
    app: microventa
    type: microservice