apiVersion: v1
kind: Pod
metadata:
  name: microventa-pod
  labels:
    app: microventa
    type: microservice
spec:
  containers:
    - name: microventa-app
      image: rchalco/backgroundapirest:latest
      ports:
        - containerPort: 80
      env:
        - name: conexionString
          value: Server=mssql-service;Database=DBTintoreriaGamaFac;User=sa;Password=admin.123