//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINSIncronizacion
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://siat.impuestos.gob.bo/", ConfigurationName="SINSIncronizacion.ServicioFacturacionSincronizacion")]
    internal interface ServicioFacturacionSincronizacion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaMotivoAnulacionResponse> sincronizarParametricaMotivoAnulacionAsync(SINSIncronizacion.sincronizarParametricaMotivoAnulacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarActividadesResponse> sincronizarActividadesAsync(SINSIncronizacion.sincronizarActividades request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarFechaHoraResponse> sincronizarFechaHoraAsync(SINSIncronizacion.sincronizarFechaHora request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarListaLeyendasFacturaResponse> sincronizarListaLeyendasFacturaAsync(SINSIncronizacion.sincronizarListaLeyendasFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoHabitacionResponse> sincronizarParametricaTipoHabitacionAsync(SINSIncronizacion.sincronizarParametricaTipoHabitacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarListaActividadesDocumentoSectorResponse> sincronizarListaActividadesDocumentoSectorAsync(SINSIncronizacion.sincronizarListaActividadesDocumentoSector request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoDocumentoIdentidadResponse> sincronizarParametricaTipoDocumentoIdentidadAsync(SINSIncronizacion.sincronizarParametricaTipoDocumentoIdentidad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaUnidadMedidaResponse> sincronizarParametricaUnidadMedidaAsync(SINSIncronizacion.sincronizarParametricaUnidadMedida request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoDocumentoSectorResponse> sincronizarParametricaTipoDocumentoSectorAsync(SINSIncronizacion.sincronizarParametricaTipoDocumentoSector request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTiposFacturaResponse> sincronizarParametricaTiposFacturaAsync(SINSIncronizacion.sincronizarParametricaTiposFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.verificarComunicacionResponse> verificarComunicacionAsync(SINSIncronizacion.verificarComunicacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarListaMensajesServiciosResponse> sincronizarListaMensajesServiciosAsync(SINSIncronizacion.sincronizarListaMensajesServicios request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoMetodoPagoResponse> sincronizarParametricaTipoMetodoPagoAsync(SINSIncronizacion.sincronizarParametricaTipoMetodoPago request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaEventosSignificativosResponse> sincronizarParametricaEventosSignificativosAsync(SINSIncronizacion.sincronizarParametricaEventosSignificativos request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoPuntoVentaResponse> sincronizarParametricaTipoPuntoVentaAsync(SINSIncronizacion.sincronizarParametricaTipoPuntoVenta request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarListaProductosServiciosResponse> sincronizarListaProductosServiciosAsync(SINSIncronizacion.sincronizarListaProductosServicios request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoEmisionResponse> sincronizarParametricaTipoEmisionAsync(SINSIncronizacion.sincronizarParametricaTipoEmision request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaPaisOrigenResponse> sincronizarParametricaPaisOrigenAsync(SINSIncronizacion.sincronizarParametricaPaisOrigen request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoMonedaResponse> sincronizarParametricaTipoMonedaAsync(SINSIncronizacion.sincronizarParametricaTipoMoneda request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudSincronizacion
    {
        
        private int codigoAmbienteField;
        
        private System.Nullable<int> codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cuisField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class productosDto
    {
        
        private string codigoActividadField;
        
        private long codigoProductoField;
        
        private bool codigoProductoFieldSpecified;
        
        private string descripcionProductoField;
        
        private string[] nandinaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoActividad
        {
            get
            {
                return this.codigoActividadField;
            }
            set
            {
                this.codigoActividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long codigoProducto
        {
            get
            {
                return this.codigoProductoField;
            }
            set
            {
                this.codigoProductoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoProductoSpecified
        {
            get
            {
                return this.codigoProductoFieldSpecified;
            }
            set
            {
                this.codigoProductoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcionProducto
        {
            get
            {
                return this.descripcionProductoField;
            }
            set
            {
                this.descripcionProductoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nandina", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string[] nandina
        {
            get
            {
                return this.nandinaField;
            }
            set
            {
                this.nandinaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class parametricaLeyendasDto
    {
        
        private string codigoActividadField;
        
        private string descripcionLeyendaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoActividad
        {
            get
            {
                return this.codigoActividadField;
            }
            set
            {
                this.codigoActividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcionLeyenda
        {
            get
            {
                return this.descripcionLeyendaField;
            }
            set
            {
                this.descripcionLeyendaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class actividadesDto
    {
        
        private string codigoCaebField;
        
        private string descripcionField;
        
        private string tipoActividadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoCaeb
        {
            get
            {
                return this.codigoCaebField;
            }
            set
            {
                this.codigoCaebField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tipoActividad
        {
            get
            {
                return this.tipoActividadField;
            }
            set
            {
                this.tipoActividadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class parametricasDto
    {
        
        private int codigoClasificadorField;
        
        private bool codigoClasificadorFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoClasificador
        {
            get
            {
                return this.codigoClasificadorField;
            }
            set
            {
                this.codigoClasificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoClasificadorSpecified
        {
            get
            {
                return this.codigoClasificadorFieldSpecified;
            }
            set
            {
                this.codigoClasificadorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(modelDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(actividadesDocumentoSectorDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaConfiguracion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaProductos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaActividadesDocumentoSector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaParametricasLeyendas))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaFechaHora))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaActividades))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaParametricas))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class model
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(actividadesDocumentoSectorDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaConfiguracion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaProductos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaActividadesDocumentoSector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaParametricasLeyendas))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaFechaHora))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaActividades))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaParametricas))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class modelDto : model
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaComunicacion : modelDto
    {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeServicio : modelDto
    {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified
        {
            get
            {
                return this.codigoFieldSpecified;
            }
            set
            {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class actividadesDocumentoSectorDto : modelDto
    {
        
        private string codigoActividadField;
        
        private int codigoDocumentoSectorField;
        
        private bool codigoDocumentoSectorFieldSpecified;
        
        private string tipoDocumentoSectorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoActividad
        {
            get
            {
                return this.codigoActividadField;
            }
            set
            {
                this.codigoActividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoDocumentoSector
        {
            get
            {
                return this.codigoDocumentoSectorField;
            }
            set
            {
                this.codigoDocumentoSectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoDocumentoSectorSpecified
        {
            get
            {
                return this.codigoDocumentoSectorFieldSpecified;
            }
            set
            {
                this.codigoDocumentoSectorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tipoDocumentoSector
        {
            get
            {
                return this.tipoDocumentoSectorField;
            }
            set
            {
                this.tipoDocumentoSectorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaProductos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaActividadesDocumentoSector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaParametricasLeyendas))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaFechaHora))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaActividades))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListaParametricas))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaConfiguracion : modelDto
    {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaListaProductos : respuestaConfiguracion
    {
        
        private productosDto[] listaCodigosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaCodigos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public productosDto[] listaCodigos
        {
            get
            {
                return this.listaCodigosField;
            }
            set
            {
                this.listaCodigosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaListaActividadesDocumentoSector : respuestaConfiguracion
    {
        
        private actividadesDocumentoSectorDto[] listaActividadesDocumentoSectorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaActividadesDocumentoSector", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public actividadesDocumentoSectorDto[] listaActividadesDocumentoSector
        {
            get
            {
                return this.listaActividadesDocumentoSectorField;
            }
            set
            {
                this.listaActividadesDocumentoSectorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaListaParametricasLeyendas : respuestaConfiguracion
    {
        
        private parametricaLeyendasDto[] listaLeyendasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaLeyendas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public parametricaLeyendasDto[] listaLeyendas
        {
            get
            {
                return this.listaLeyendasField;
            }
            set
            {
                this.listaLeyendasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaFechaHora : respuestaConfiguracion
    {
        
        private string fechaHoraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fechaHora
        {
            get
            {
                return this.fechaHoraField;
            }
            set
            {
                this.fechaHoraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaListaActividades : respuestaConfiguracion
    {
        
        private actividadesDto[] listaActividadesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaActividades", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public actividadesDto[] listaActividades
        {
            get
            {
                return this.listaActividadesField;
            }
            set
            {
                this.listaActividadesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaListaParametricas : respuestaConfiguracion
    {
        
        private parametricasDto[] listaCodigosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaCodigos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public parametricasDto[] listaCodigos
        {
            get
            {
                return this.listaCodigosField;
            }
            set
            {
                this.listaCodigosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaMotivoAnulacion", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaMotivoAnulacion
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarParametricaMotivoAnulacion()
        {
        }
        
        public sincronizarParametricaMotivoAnulacion(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaMotivoAnulacionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaMotivoAnulacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas;
        
        public sincronizarParametricaMotivoAnulacionResponse()
        {
        }
        
        public sincronizarParametricaMotivoAnulacionResponse(SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas)
        {
            this.RespuestaListaParametricas = RespuestaListaParametricas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarActividades", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarActividades
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarActividades()
        {
        }
        
        public sincronizarActividades(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarActividadesResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarActividadesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaActividades RespuestaListaActividades;
        
        public sincronizarActividadesResponse()
        {
        }
        
        public sincronizarActividadesResponse(SINSIncronizacion.respuestaListaActividades RespuestaListaActividades)
        {
            this.RespuestaListaActividades = RespuestaListaActividades;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarFechaHora", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarFechaHora
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarFechaHora()
        {
        }
        
        public sincronizarFechaHora(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarFechaHoraResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarFechaHoraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaFechaHora RespuestaFechaHora;
        
        public sincronizarFechaHoraResponse()
        {
        }
        
        public sincronizarFechaHoraResponse(SINSIncronizacion.respuestaFechaHora RespuestaFechaHora)
        {
            this.RespuestaFechaHora = RespuestaFechaHora;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarListaLeyendasFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarListaLeyendasFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarListaLeyendasFactura()
        {
        }
        
        public sincronizarListaLeyendasFactura(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarListaLeyendasFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarListaLeyendasFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricasLeyendas RespuestaListaParametricasLeyendas;
        
        public sincronizarListaLeyendasFacturaResponse()
        {
        }
        
        public sincronizarListaLeyendasFacturaResponse(SINSIncronizacion.respuestaListaParametricasLeyendas RespuestaListaParametricasLeyendas)
        {
            this.RespuestaListaParametricasLeyendas = RespuestaListaParametricasLeyendas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoHabitacion", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoHabitacion
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarParametricaTipoHabitacion()
        {
        }
        
        public sincronizarParametricaTipoHabitacion(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoHabitacionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoHabitacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas;
        
        public sincronizarParametricaTipoHabitacionResponse()
        {
        }
        
        public sincronizarParametricaTipoHabitacionResponse(SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas)
        {
            this.RespuestaListaParametricas = RespuestaListaParametricas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarListaActividadesDocumentoSector", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarListaActividadesDocumentoSector
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarListaActividadesDocumentoSector()
        {
        }
        
        public sincronizarListaActividadesDocumentoSector(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarListaActividadesDocumentoSectorResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarListaActividadesDocumentoSectorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaActividadesDocumentoSector RespuestaListaActividadesDocumentoSector;
        
        public sincronizarListaActividadesDocumentoSectorResponse()
        {
        }
        
        public sincronizarListaActividadesDocumentoSectorResponse(SINSIncronizacion.respuestaListaActividadesDocumentoSector RespuestaListaActividadesDocumentoSector)
        {
            this.RespuestaListaActividadesDocumentoSector = RespuestaListaActividadesDocumentoSector;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoDocumentoIdentidad", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoDocumentoIdentidad
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarParametricaTipoDocumentoIdentidad()
        {
        }
        
        public sincronizarParametricaTipoDocumentoIdentidad(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoDocumentoIdentidadResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoDocumentoIdentidadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas;
        
        public sincronizarParametricaTipoDocumentoIdentidadResponse()
        {
        }
        
        public sincronizarParametricaTipoDocumentoIdentidadResponse(SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas)
        {
            this.RespuestaListaParametricas = RespuestaListaParametricas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaUnidadMedida", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaUnidadMedida
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarParametricaUnidadMedida()
        {
        }
        
        public sincronizarParametricaUnidadMedida(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaUnidadMedidaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaUnidadMedidaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas;
        
        public sincronizarParametricaUnidadMedidaResponse()
        {
        }
        
        public sincronizarParametricaUnidadMedidaResponse(SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas)
        {
            this.RespuestaListaParametricas = RespuestaListaParametricas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoDocumentoSector", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoDocumentoSector
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarParametricaTipoDocumentoSector()
        {
        }
        
        public sincronizarParametricaTipoDocumentoSector(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoDocumentoSectorResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoDocumentoSectorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas;
        
        public sincronizarParametricaTipoDocumentoSectorResponse()
        {
        }
        
        public sincronizarParametricaTipoDocumentoSectorResponse(SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas)
        {
            this.RespuestaListaParametricas = RespuestaListaParametricas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTiposFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTiposFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarParametricaTiposFactura()
        {
        }
        
        public sincronizarParametricaTiposFactura(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTiposFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTiposFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas;
        
        public sincronizarParametricaTiposFacturaResponse()
        {
        }
        
        public sincronizarParametricaTiposFacturaResponse(SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas)
        {
            this.RespuestaListaParametricas = RespuestaListaParametricas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacion", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class verificarComunicacion
    {
        
        public verificarComunicacion()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class verificarComunicacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaComunicacion @return;
        
        public verificarComunicacionResponse()
        {
        }
        
        public verificarComunicacionResponse(SINSIncronizacion.respuestaComunicacion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarListaMensajesServicios", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarListaMensajesServicios
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarListaMensajesServicios()
        {
        }
        
        public sincronizarListaMensajesServicios(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarListaMensajesServiciosResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarListaMensajesServiciosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas;
        
        public sincronizarListaMensajesServiciosResponse()
        {
        }
        
        public sincronizarListaMensajesServiciosResponse(SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas)
        {
            this.RespuestaListaParametricas = RespuestaListaParametricas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoMetodoPago", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoMetodoPago
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarParametricaTipoMetodoPago()
        {
        }
        
        public sincronizarParametricaTipoMetodoPago(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoMetodoPagoResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoMetodoPagoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas;
        
        public sincronizarParametricaTipoMetodoPagoResponse()
        {
        }
        
        public sincronizarParametricaTipoMetodoPagoResponse(SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas)
        {
            this.RespuestaListaParametricas = RespuestaListaParametricas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaEventosSignificativos", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaEventosSignificativos
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarParametricaEventosSignificativos()
        {
        }
        
        public sincronizarParametricaEventosSignificativos(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaEventosSignificativosResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaEventosSignificativosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas;
        
        public sincronizarParametricaEventosSignificativosResponse()
        {
        }
        
        public sincronizarParametricaEventosSignificativosResponse(SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas)
        {
            this.RespuestaListaParametricas = RespuestaListaParametricas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoPuntoVenta", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoPuntoVenta
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarParametricaTipoPuntoVenta()
        {
        }
        
        public sincronizarParametricaTipoPuntoVenta(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoPuntoVentaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoPuntoVentaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas;
        
        public sincronizarParametricaTipoPuntoVentaResponse()
        {
        }
        
        public sincronizarParametricaTipoPuntoVentaResponse(SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas)
        {
            this.RespuestaListaParametricas = RespuestaListaParametricas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarListaProductosServicios", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarListaProductosServicios
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarListaProductosServicios()
        {
        }
        
        public sincronizarListaProductosServicios(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarListaProductosServiciosResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarListaProductosServiciosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaProductos RespuestaListaProductos;
        
        public sincronizarListaProductosServiciosResponse()
        {
        }
        
        public sincronizarListaProductosServiciosResponse(SINSIncronizacion.respuestaListaProductos RespuestaListaProductos)
        {
            this.RespuestaListaProductos = RespuestaListaProductos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoEmision", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoEmision
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarParametricaTipoEmision()
        {
        }
        
        public sincronizarParametricaTipoEmision(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoEmisionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoEmisionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas;
        
        public sincronizarParametricaTipoEmisionResponse()
        {
        }
        
        public sincronizarParametricaTipoEmisionResponse(SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas)
        {
            this.RespuestaListaParametricas = RespuestaListaParametricas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaPaisOrigen", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaPaisOrigen
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarParametricaPaisOrigen()
        {
        }
        
        public sincronizarParametricaPaisOrigen(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaPaisOrigenResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaPaisOrigenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas;
        
        public sincronizarParametricaPaisOrigenResponse()
        {
        }
        
        public sincronizarParametricaPaisOrigenResponse(SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas)
        {
            this.RespuestaListaParametricas = RespuestaListaParametricas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoMoneda", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoMoneda
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion;
        
        public sincronizarParametricaTipoMoneda()
        {
        }
        
        public sincronizarParametricaTipoMoneda(SINSIncronizacion.solicitudSincronizacion SolicitudSincronizacion)
        {
            this.SolicitudSincronizacion = SolicitudSincronizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarParametricaTipoMonedaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class sincronizarParametricaTipoMonedaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas;
        
        public sincronizarParametricaTipoMonedaResponse()
        {
        }
        
        public sincronizarParametricaTipoMonedaResponse(SINSIncronizacion.respuestaListaParametricas RespuestaListaParametricas)
        {
            this.RespuestaListaParametricas = RespuestaListaParametricas;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    internal interface ServicioFacturacionSincronizacionChannel : SINSIncronizacion.ServicioFacturacionSincronizacion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    internal partial class ServicioFacturacionSincronizacionClient : System.ServiceModel.ClientBase<SINSIncronizacion.ServicioFacturacionSincronizacion>, SINSIncronizacion.ServicioFacturacionSincronizacion
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioFacturacionSincronizacionClient() : 
                base(ServicioFacturacionSincronizacionClient.GetDefaultBinding(), ServicioFacturacionSincronizacionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicioFacturacionSincronizacionPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionSincronizacionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioFacturacionSincronizacionClient.GetBindingForEndpoint(endpointConfiguration), ServicioFacturacionSincronizacionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionSincronizacionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioFacturacionSincronizacionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionSincronizacionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioFacturacionSincronizacionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionSincronizacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaMotivoAnulacionResponse> sincronizarParametricaMotivoAnulacionAsync(SINSIncronizacion.sincronizarParametricaMotivoAnulacion request)
        {
            return base.Channel.sincronizarParametricaMotivoAnulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarActividadesResponse> sincronizarActividadesAsync(SINSIncronizacion.sincronizarActividades request)
        {
            return base.Channel.sincronizarActividadesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarFechaHoraResponse> sincronizarFechaHoraAsync(SINSIncronizacion.sincronizarFechaHora request)
        {
            return base.Channel.sincronizarFechaHoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarListaLeyendasFacturaResponse> sincronizarListaLeyendasFacturaAsync(SINSIncronizacion.sincronizarListaLeyendasFactura request)
        {
            return base.Channel.sincronizarListaLeyendasFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoHabitacionResponse> sincronizarParametricaTipoHabitacionAsync(SINSIncronizacion.sincronizarParametricaTipoHabitacion request)
        {
            return base.Channel.sincronizarParametricaTipoHabitacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarListaActividadesDocumentoSectorResponse> sincronizarListaActividadesDocumentoSectorAsync(SINSIncronizacion.sincronizarListaActividadesDocumentoSector request)
        {
            return base.Channel.sincronizarListaActividadesDocumentoSectorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoDocumentoIdentidadResponse> sincronizarParametricaTipoDocumentoIdentidadAsync(SINSIncronizacion.sincronizarParametricaTipoDocumentoIdentidad request)
        {
            return base.Channel.sincronizarParametricaTipoDocumentoIdentidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaUnidadMedidaResponse> sincronizarParametricaUnidadMedidaAsync(SINSIncronizacion.sincronizarParametricaUnidadMedida request)
        {
            return base.Channel.sincronizarParametricaUnidadMedidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoDocumentoSectorResponse> sincronizarParametricaTipoDocumentoSectorAsync(SINSIncronizacion.sincronizarParametricaTipoDocumentoSector request)
        {
            return base.Channel.sincronizarParametricaTipoDocumentoSectorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTiposFacturaResponse> sincronizarParametricaTiposFacturaAsync(SINSIncronizacion.sincronizarParametricaTiposFactura request)
        {
            return base.Channel.sincronizarParametricaTiposFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.verificarComunicacionResponse> verificarComunicacionAsync(SINSIncronizacion.verificarComunicacion request)
        {
            return base.Channel.verificarComunicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarListaMensajesServiciosResponse> sincronizarListaMensajesServiciosAsync(SINSIncronizacion.sincronizarListaMensajesServicios request)
        {
            return base.Channel.sincronizarListaMensajesServiciosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoMetodoPagoResponse> sincronizarParametricaTipoMetodoPagoAsync(SINSIncronizacion.sincronizarParametricaTipoMetodoPago request)
        {
            return base.Channel.sincronizarParametricaTipoMetodoPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaEventosSignificativosResponse> sincronizarParametricaEventosSignificativosAsync(SINSIncronizacion.sincronizarParametricaEventosSignificativos request)
        {
            return base.Channel.sincronizarParametricaEventosSignificativosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoPuntoVentaResponse> sincronizarParametricaTipoPuntoVentaAsync(SINSIncronizacion.sincronizarParametricaTipoPuntoVenta request)
        {
            return base.Channel.sincronizarParametricaTipoPuntoVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarListaProductosServiciosResponse> sincronizarListaProductosServiciosAsync(SINSIncronizacion.sincronizarListaProductosServicios request)
        {
            return base.Channel.sincronizarListaProductosServiciosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoEmisionResponse> sincronizarParametricaTipoEmisionAsync(SINSIncronizacion.sincronizarParametricaTipoEmision request)
        {
            return base.Channel.sincronizarParametricaTipoEmisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaPaisOrigenResponse> sincronizarParametricaPaisOrigenAsync(SINSIncronizacion.sincronizarParametricaPaisOrigen request)
        {
            return base.Channel.sincronizarParametricaPaisOrigenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINSIncronizacion.sincronizarParametricaTipoMonedaResponse> sincronizarParametricaTipoMonedaAsync(SINSIncronizacion.sincronizarParametricaTipoMoneda request)
        {
            return base.Channel.sincronizarParametricaTipoMonedaAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioFacturacionSincronizacionPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioFacturacionSincronizacionPort))
            {
                return new System.ServiceModel.EndpointAddress("https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionSincronizacion");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioFacturacionSincronizacionClient.GetBindingForEndpoint(EndpointConfiguration.ServicioFacturacionSincronizacionPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioFacturacionSincronizacionClient.GetEndpointAddress(EndpointConfiguration.ServicioFacturacionSincronizacionPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioFacturacionSincronizacionPort,
        }
    }
}
