//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.FirmaDigital {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.prodemsign.bo.prodem.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.prodemsign.bo.prodem.com/")]
    public partial class resulSign : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isValidField;
        
        private string messageField;
        
        private string resulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool isValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
                this.RaisePropertyChanged("isValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string resul {
            get {
                return this.resulField;
            }
            set {
                this.resulField = value;
                this.RaisePropertyChanged("resul");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.prodemsign.bo.prodem.com/", ConfigurationName="FirmaDigital.SignDocument")]
    public interface SignDocument {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsApp1.FirmaDigital.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.FirmaDigital.GetDocumentSignResponse GetDocumentSign(WindowsFormsApp1.FirmaDigital.GetDocumentSign request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.FirmaDigital.GetDocumentSignResponse> GetDocumentSignAsync(WindowsFormsApp1.FirmaDigital.GetDocumentSign request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.FirmaDigital.helloResponse hello(WindowsFormsApp1.FirmaDigital.hello request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.FirmaDigital.helloResponse> helloAsync(WindowsFormsApp1.FirmaDigital.hello request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentSign", WrapperNamespace="http://services.prodemsign.bo.prodem.com/", IsWrapped=true)]
    public partial class GetDocumentSign {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.prodemsign.bo.prodem.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Certificate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.prodemsign.bo.prodem.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Content;
        
        public GetDocumentSign() {
        }
        
        public GetDocumentSign(string Certificate, string Content) {
            this.Certificate = Certificate;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentSignResponse", WrapperNamespace="http://services.prodemsign.bo.prodem.com/", IsWrapped=true)]
    public partial class GetDocumentSignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.prodemsign.bo.prodem.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FirmaDigital.resulSign @return;
        
        public GetDocumentSignResponse() {
        }
        
        public GetDocumentSignResponse(WindowsFormsApp1.FirmaDigital.resulSign @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://services.prodemsign.bo.prodem.com/", IsWrapped=true)]
    public partial class hello {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.prodemsign.bo.prodem.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public hello() {
        }
        
        public hello(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://services.prodemsign.bo.prodem.com/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.prodemsign.bo.prodem.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SignDocumentChannel : WindowsFormsApp1.FirmaDigital.SignDocument, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignDocumentClient : System.ServiceModel.ClientBase<WindowsFormsApp1.FirmaDigital.SignDocument>, WindowsFormsApp1.FirmaDigital.SignDocument {
        
        public SignDocumentClient() {
        }
        
        public SignDocumentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignDocumentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignDocumentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignDocumentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.FirmaDigital.GetDocumentSignResponse WindowsFormsApp1.FirmaDigital.SignDocument.GetDocumentSign(WindowsFormsApp1.FirmaDigital.GetDocumentSign request) {
            return base.Channel.GetDocumentSign(request);
        }
        
        public WindowsFormsApp1.FirmaDigital.resulSign GetDocumentSign(string Certificate, string Content) {
            WindowsFormsApp1.FirmaDigital.GetDocumentSign inValue = new WindowsFormsApp1.FirmaDigital.GetDocumentSign();
            inValue.Certificate = Certificate;
            inValue.Content = Content;
            WindowsFormsApp1.FirmaDigital.GetDocumentSignResponse retVal = ((WindowsFormsApp1.FirmaDigital.SignDocument)(this)).GetDocumentSign(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.FirmaDigital.GetDocumentSignResponse> WindowsFormsApp1.FirmaDigital.SignDocument.GetDocumentSignAsync(WindowsFormsApp1.FirmaDigital.GetDocumentSign request) {
            return base.Channel.GetDocumentSignAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.FirmaDigital.GetDocumentSignResponse> GetDocumentSignAsync(string Certificate, string Content) {
            WindowsFormsApp1.FirmaDigital.GetDocumentSign inValue = new WindowsFormsApp1.FirmaDigital.GetDocumentSign();
            inValue.Certificate = Certificate;
            inValue.Content = Content;
            return ((WindowsFormsApp1.FirmaDigital.SignDocument)(this)).GetDocumentSignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.FirmaDigital.helloResponse WindowsFormsApp1.FirmaDigital.SignDocument.hello(WindowsFormsApp1.FirmaDigital.hello request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WindowsFormsApp1.FirmaDigital.hello inValue = new WindowsFormsApp1.FirmaDigital.hello();
            inValue.name = name;
            WindowsFormsApp1.FirmaDigital.helloResponse retVal = ((WindowsFormsApp1.FirmaDigital.SignDocument)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.FirmaDigital.helloResponse> WindowsFormsApp1.FirmaDigital.SignDocument.helloAsync(WindowsFormsApp1.FirmaDigital.hello request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.FirmaDigital.helloResponse> helloAsync(string name) {
            WindowsFormsApp1.FirmaDigital.hello inValue = new WindowsFormsApp1.FirmaDigital.hello();
            inValue.name = name;
            return ((WindowsFormsApp1.FirmaDigital.SignDocument)(this)).helloAsync(inValue);
        }
    }
}
