//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabeceraFac2
    {
        public long idCabeceraFac { get; set; }
        public long nitEmisor { get; set; }
        public string razonSocialEmisor { get; set; }
        public string municipio { get; set; }
        public string telefono { get; set; }
        public Nullable<long> numeroFactura { get; set; }
        public string Cuf { get; set; }
        public string cufd { get; set; }
        public Nullable<long> codigoSucursal { get; set; }
        public string direccion { get; set; }
        public Nullable<long> codigoPuntoVenta { get; set; }
        public Nullable<System.DateTime> fechaEmision { get; set; }
        public string nombreRazonSocial { get; set; }
        public Nullable<long> codigoTipoDocumentoIdentidad { get; set; }
        public string numeroDocumento { get; set; }
        public string complemento { get; set; }
        public string codigoCliente { get; set; }
        public Nullable<long> codigoMetodoPago { get; set; }
        public string numeroTarjeta { get; set; }
        public Nullable<decimal> montoTotalArrendamientoFinanciero { get; set; }
        public Nullable<decimal> montoTotal { get; set; }
        public Nullable<decimal> montoTotalSujetoIva { get; set; }
        public Nullable<long> codigoMoneda { get; set; }
        public Nullable<long> tipoCambio { get; set; }
        public Nullable<decimal> montoTotalMoneda { get; set; }
        public Nullable<decimal> descuentoAdicional { get; set; }
        public Nullable<long> codigoExcepcion { get; set; }
        public Nullable<long> cafc { get; set; }
        public string leyenda { get; set; }
        public string usuario { get; set; }
        public Nullable<long> codigoDocumentoSector { get; set; }
        public string request { get; set; }
        public string response { get; set; }
        public string archivoXML { get; set; }
        public Nullable<bool> Procesado { get; set; }
    }
}
