//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUFD
    {
        public long IdCUFD { get; set; }
        public string CufdValue { get; set; }
        public string Cuis { get; set; }
        public int CodSucursal { get; set; }
        public string XMLRequest { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string CodigoControl { get; set; }
        public Nullable<int> CodpuntoVenta { get; set; }
        public Nullable<System.DateTime> FechaVigenciaSIN { get; set; }
    }
}
