//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuis
    {
        public long IdCUI { get; set; }
        public string CUI { get; set; }
        public string Sucursal { get; set; }
        public string XML { get; set; }
        public int IdSucursal { get; set; }
        public System.DateTime FechaHora { get; set; }
        public Nullable<int> CodPuntoVenta { get; set; }
    }
}
