//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasAnuladas
    {
        public long IdFacturaAnulada { get; set; }
        public long IdCabeceraFac { get; set; }
        public System.DateTime FechaProceso { get; set; }
        public string XMLRequest { get; set; }
        public string XMLResponse { get; set; }
        public bool Procesado { get; set; }
        public string codigoDescripcion { get; set; }
        public int codigoEstado { get; set; }
        public string codigoRecepcion { get; set; }
        public string TipoFactura { get; set; }
    }
}
