//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMasivo
    {
        public long IdLogMasivo { get; set; }
        public string Codigo { get; set; }
        public string CodigoExcepcion { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaProceso { get; set; }
        public bool Estado { get; set; }
        public string XMLRequest { get; set; }
        public string XMLResponse { get; set; }
        public long IdPruebaEvento { get; set; }
        public Nullable<long> codigoSucursal { get; set; }
        public Nullable<long> codigoPuntoVenta { get; set; }
        public Nullable<long> TipoFactura { get; set; }
        public string CodigoRecepcion { get; set; }
        public string Servicio { get; set; }
        public Nullable<long> CodigoEvento { get; set; }
    }
}
