//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruebasEventoSignificativo
    {
        public long IdPruebaEvento { get; set; }
        public int CodSucursal { get; set; }
        public int CodPuntoVenta { get; set; }
        public int codEvento { get; set; }
        public string DescripcionEvento { get; set; }
        public int IDCUFD { get; set; }
        public string CufdEvento { get; set; }
        public string XmlRequest { get; set; }
        public string XmlResponse { get; set; }
        public string CodEventoSignificativo { get; set; }
        public bool Procesado { get; set; }
        public Nullable<int> IDCUFDEVENTO { get; set; }
        public Nullable<System.DateTime> FechaHoraIni { get; set; }
        public Nullable<System.DateTime> FechaHoraFin { get; set; }
        public Nullable<int> IdRegistroEvento { get; set; }
        public string CodigoControlCUFD { get; set; }
        public string CodigoControlCUFDEvento { get; set; }
    }
}
