//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroEvento
    {
        public long IdRegistroEvento { get; set; }
        public long codigoevento { get; set; }
        public string cufdevento { get; set; }
        public string cufd { get; set; }
        public string Cui { get; set; }
        public int CodigoSucursal { get; set; }
        public int CodigoMotivoEvento { get; set; }
        public System.DateTime FechaHoraInicio { get; set; }
        public System.DateTime FechaHoraFin { get; set; }
        public System.DateTime FechaHoraRegistro { get; set; }
        public int codpuntoventa { get; set; }
        public string XMLRequest { get; set; }
        public string XMLResponse { get; set; }
    }
}
