//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIN_BDEntities2 : DbContext
    {
        public SIN_BDEntities2()
            : base("name=SIN_BDEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CabeceraFac> CabeceraFac { get; set; }
        public virtual DbSet<CUFD> CUFD { get; set; }
        public virtual DbSet<Cuis> Cuis { get; set; }
        public virtual DbSet<FacturasAnuladas> FacturasAnuladas { get; set; }
        public virtual DbSet<LogMasivo> LogMasivo { get; set; }
        public virtual DbSet<PruebasEventoSignificativo> PruebasEventoSignificativo { get; set; }
        public virtual DbSet<puntoventa> puntoventa { get; set; }
        public virtual DbSet<RegistroEvento> RegistroEvento { get; set; }
        public virtual DbSet<tProofDetailG> tProofDetailG { get; set; }
        public virtual DbSet<tProofG> tProofG { get; set; }
        public virtual DbSet<OfficeSIN> OfficeSIN { get; set; }
        public virtual DbSet<CabeceraFac2> CabeceraFac2 { get; set; }
    }
}
