//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProofG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tProofG()
        {
            this.tProofDetailG = new HashSet<tProofDetailG>();
        }
    
        public long IdProof { get; set; }
        public long IdOffice { get; set; }
        public long IdProofType { get; set; }
        public long IdUser { get; set; }
        public Nullable<decimal> TotalProofPrinter { get; set; }
        public Nullable<long> IdMoney { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProofDetailG> tProofDetailG { get; set; }
    }
}
