//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFac
    {
        public long idDetalleFac { get; set; }
        public long idCabeceraFac { get; set; }
        public long actividadEconomica { get; set; }
        public long codigoProductoSin { get; set; }
        public long codigoProducto { get; set; }
        public string descripcion { get; set; }
        public long cantidad { get; set; }
        public long unidadMedida { get; set; }
        public Nullable<decimal> precioUnitario { get; set; }
        public Nullable<decimal> montoDescuento { get; set; }
        public Nullable<decimal> subTotal { get; set; }
        public string detalle { get; set; }
    }
}
