//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.FacturacionCodigos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://siat.impuestos.gob.bo/", ConfigurationName="FacturacionCodigos.ServicioFacturacionCodigos")]
    public interface ServicioFacturacionCodigos {
        
        // CODEGEN: Parameter 'RespuestaComunicacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaComunicacion")]
        WindowsFormsApp1.FacturacionCodigos.verificarComunicacionResponse verificarComunicacion(WindowsFormsApp1.FacturacionCodigos.verificarComunicacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.verificarComunicacionResponse> verificarComunicacionAsync(WindowsFormsApp1.FacturacionCodigos.verificarComunicacion request);
        
        // CODEGEN: Parameter 'RespuestaVerificarNit' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaVerificarNit")]
        WindowsFormsApp1.FacturacionCodigos.verificarNitResponse verificarNit(WindowsFormsApp1.FacturacionCodigos.verificarNit request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.verificarNitResponse> verificarNitAsync(WindowsFormsApp1.FacturacionCodigos.verificarNit request);
        
        // CODEGEN: Parameter 'RespuestaCuisMasivo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaCuisMasivo")]
        WindowsFormsApp1.FacturacionCodigos.cuisMasivoResponse cuisMasivo(WindowsFormsApp1.FacturacionCodigos.cuisMasivo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.cuisMasivoResponse> cuisMasivoAsync(WindowsFormsApp1.FacturacionCodigos.cuisMasivo request);
        
        // CODEGEN: Parameter 'RespuestaCufd' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaCufd")]
        WindowsFormsApp1.FacturacionCodigos.cufdResponse cufd(WindowsFormsApp1.FacturacionCodigos.cufd request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.cufdResponse> cufdAsync(WindowsFormsApp1.FacturacionCodigos.cufd request);
        
        // CODEGEN: Parameter 'RespuestaNotificaRevocado' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaNotificaRevocado")]
        WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocadoResponse notificaCertificadoRevocado(WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocado request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocadoResponse> notificaCertificadoRevocadoAsync(WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocado request);
        
        // CODEGEN: Parameter 'RespuestaCuis' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaCuis")]
        WindowsFormsApp1.FacturacionCodigos.cuisResponse cuis(WindowsFormsApp1.FacturacionCodigos.cuis request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.cuisResponse> cuisAsync(WindowsFormsApp1.FacturacionCodigos.cuis request);
        
        // CODEGEN: Parameter 'RespuestaCufdMasivo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaCufdMasivo")]
        WindowsFormsApp1.FacturacionCodigos.cufdMasivoResponse cufdMasivo(WindowsFormsApp1.FacturacionCodigos.cufdMasivo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.cufdMasivoResponse> cufdMasivoAsync(WindowsFormsApp1.FacturacionCodigos.cufdMasivo request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaComunicacion : modelDto {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList {
            get {
                return this.mensajesListField;
            }
            set {
                this.mensajesListField = value;
                this.RaisePropertyChanged("mensajesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified {
            get {
                return this.transaccionFieldSpecified;
            }
            set {
                this.transaccionFieldSpecified = value;
                this.RaisePropertyChanged("transaccionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeServicio : modelDto {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCufdMasivo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCuis))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCufd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCuisMasivo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaConfiguracion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaNotificaRevocado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaVerificarNit))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class modelDto : model {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(modelDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCufdMasivo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCuis))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCufd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCuisMasivo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaConfiguracion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaNotificaRevocado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaVerificarNit))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class model : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudListaCufdDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private int codigoSucursalField;
        
        private string cuisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoPuntoVenta {
            get {
                return this.codigoPuntoVentaField;
            }
            set {
                this.codigoPuntoVentaField = value;
                this.RaisePropertyChanged("codigoPuntoVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified {
            get {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set {
                this.codigoPuntoVentaFieldSpecified = value;
                this.RaisePropertyChanged("codigoPuntoVentaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
                this.RaisePropertyChanged("codigoSucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cuis {
            get {
                return this.cuisField;
            }
            set {
                this.cuisField = value;
                this.RaisePropertyChanged("cuis");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCufdMasivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private string codigoSistemaField;
        
        private solicitudListaCufdDto[] datosSolicitudField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente {
            get {
                return this.codigoAmbienteField;
            }
            set {
                this.codigoAmbienteField = value;
                this.RaisePropertyChanged("codigoAmbiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad {
            get {
                return this.codigoModalidadField;
            }
            set {
                this.codigoModalidadField = value;
                this.RaisePropertyChanged("codigoModalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
                this.RaisePropertyChanged("codigoSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datosSolicitud", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public solicitudListaCufdDto[] datosSolicitud {
            get {
                return this.datosSolicitudField;
            }
            set {
                this.datosSolicitudField = value;
                this.RaisePropertyChanged("datosSolicitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
                this.RaisePropertyChanged("nit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCuis : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private System.Nullable<int> codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente {
            get {
                return this.codigoAmbienteField;
            }
            set {
                this.codigoAmbienteField = value;
                this.RaisePropertyChanged("codigoAmbiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad {
            get {
                return this.codigoModalidadField;
            }
            set {
                this.codigoModalidadField = value;
                this.RaisePropertyChanged("codigoModalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> codigoPuntoVenta {
            get {
                return this.codigoPuntoVentaField;
            }
            set {
                this.codigoPuntoVentaField = value;
                this.RaisePropertyChanged("codigoPuntoVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified {
            get {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set {
                this.codigoPuntoVentaFieldSpecified = value;
                this.RaisePropertyChanged("codigoPuntoVentaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
                this.RaisePropertyChanged("codigoSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
                this.RaisePropertyChanged("codigoSucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
                this.RaisePropertyChanged("nit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudNotifcaRevocado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string certificadoField;
        
        private int codigoAmbienteField;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cuisField;
        
        private System.Nullable<System.DateTime> fechaRevocacionField;
        
        private bool fechaRevocacionFieldSpecified;
        
        private long nitField;
        
        private string razonRevocacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string certificado {
            get {
                return this.certificadoField;
            }
            set {
                this.certificadoField = value;
                this.RaisePropertyChanged("certificado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoAmbiente {
            get {
                return this.codigoAmbienteField;
            }
            set {
                this.codigoAmbienteField = value;
                this.RaisePropertyChanged("codigoAmbiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
                this.RaisePropertyChanged("codigoSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
                this.RaisePropertyChanged("codigoSucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cuis {
            get {
                return this.cuisField;
            }
            set {
                this.cuisField = value;
                this.RaisePropertyChanged("cuis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> fechaRevocacion {
            get {
                return this.fechaRevocacionField;
            }
            set {
                this.fechaRevocacionField = value;
                this.RaisePropertyChanged("fechaRevocacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRevocacionSpecified {
            get {
                return this.fechaRevocacionFieldSpecified;
            }
            set {
                this.fechaRevocacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaRevocacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
                this.RaisePropertyChanged("nit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string razonRevocacion {
            get {
                return this.razonRevocacionField;
            }
            set {
                this.razonRevocacionField = value;
                this.RaisePropertyChanged("razonRevocacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCufd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private System.Nullable<int> codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cuisField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente {
            get {
                return this.codigoAmbienteField;
            }
            set {
                this.codigoAmbienteField = value;
                this.RaisePropertyChanged("codigoAmbiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad {
            get {
                return this.codigoModalidadField;
            }
            set {
                this.codigoModalidadField = value;
                this.RaisePropertyChanged("codigoModalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> codigoPuntoVenta {
            get {
                return this.codigoPuntoVentaField;
            }
            set {
                this.codigoPuntoVentaField = value;
                this.RaisePropertyChanged("codigoPuntoVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified {
            get {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set {
                this.codigoPuntoVentaFieldSpecified = value;
                this.RaisePropertyChanged("codigoPuntoVentaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
                this.RaisePropertyChanged("codigoSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
                this.RaisePropertyChanged("codigoSucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string cuis {
            get {
                return this.cuisField;
            }
            set {
                this.cuisField = value;
                this.RaisePropertyChanged("cuis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
                this.RaisePropertyChanged("nit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudListaCuisDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private int codigoSucursalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoPuntoVenta {
            get {
                return this.codigoPuntoVentaField;
            }
            set {
                this.codigoPuntoVentaField = value;
                this.RaisePropertyChanged("codigoPuntoVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified {
            get {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set {
                this.codigoPuntoVentaFieldSpecified = value;
                this.RaisePropertyChanged("codigoPuntoVentaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
                this.RaisePropertyChanged("codigoSucursal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCuisMasivoSistemas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private string codigoSistemaField;
        
        private solicitudListaCuisDto[] datosSolicitudField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente {
            get {
                return this.codigoAmbienteField;
            }
            set {
                this.codigoAmbienteField = value;
                this.RaisePropertyChanged("codigoAmbiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad {
            get {
                return this.codigoModalidadField;
            }
            set {
                this.codigoModalidadField = value;
                this.RaisePropertyChanged("codigoModalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
                this.RaisePropertyChanged("codigoSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datosSolicitud", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public solicitudListaCuisDto[] datosSolicitud {
            get {
                return this.datosSolicitudField;
            }
            set {
                this.datosSolicitudField = value;
                this.RaisePropertyChanged("datosSolicitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
                this.RaisePropertyChanged("nit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudVerificarNit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cuisField;
        
        private long nitField;
        
        private long nitParaVerificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente {
            get {
                return this.codigoAmbienteField;
            }
            set {
                this.codigoAmbienteField = value;
                this.RaisePropertyChanged("codigoAmbiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad {
            get {
                return this.codigoModalidadField;
            }
            set {
                this.codigoModalidadField = value;
                this.RaisePropertyChanged("codigoModalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
                this.RaisePropertyChanged("codigoSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
                this.RaisePropertyChanged("codigoSucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cuis {
            get {
                return this.cuisField;
            }
            set {
                this.cuisField = value;
                this.RaisePropertyChanged("cuis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
                this.RaisePropertyChanged("nit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long nitParaVerificacion {
            get {
                return this.nitParaVerificacionField;
            }
            set {
                this.nitParaVerificacionField = value;
                this.RaisePropertyChanged("nitParaVerificacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaListaRegistroCufdSoapDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codigoControlField;
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private int codigoSucursalField;
        
        private bool codigoSucursalFieldSpecified;
        
        private string cuisField;
        
        private string direccionField;
        
        private System.DateTime fechaVigenciaField;
        
        private bool fechaVigenciaFieldSpecified;
        
        private mensajeServicio[] mensajeServicioListField;
        
        private bool transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoControl {
            get {
                return this.codigoControlField;
            }
            set {
                this.codigoControlField = value;
                this.RaisePropertyChanged("codigoControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigoPuntoVenta {
            get {
                return this.codigoPuntoVentaField;
            }
            set {
                this.codigoPuntoVentaField = value;
                this.RaisePropertyChanged("codigoPuntoVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified {
            get {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set {
                this.codigoPuntoVentaFieldSpecified = value;
                this.RaisePropertyChanged("codigoPuntoVentaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
                this.RaisePropertyChanged("codigoSucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSucursalSpecified {
            get {
                return this.codigoSucursalFieldSpecified;
            }
            set {
                this.codigoSucursalFieldSpecified = value;
                this.RaisePropertyChanged("codigoSucursalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cuis {
            get {
                return this.cuisField;
            }
            set {
                this.cuisField = value;
                this.RaisePropertyChanged("cuis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaVigencia {
            get {
                return this.fechaVigenciaField;
            }
            set {
                this.fechaVigenciaField = value;
                this.RaisePropertyChanged("fechaVigencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVigenciaSpecified {
            get {
                return this.fechaVigenciaFieldSpecified;
            }
            set {
                this.fechaVigenciaFieldSpecified = value;
                this.RaisePropertyChanged("fechaVigenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajeServicioList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public mensajeServicio[] mensajeServicioList {
            get {
                return this.mensajeServicioListField;
            }
            set {
                this.mensajeServicioListField = value;
                this.RaisePropertyChanged("mensajeServicioList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaListaRegistroCuisSoapDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private int codigoSucursalField;
        
        private bool codigoSucursalFieldSpecified;
        
        private System.DateTime fechaVigenciaField;
        
        private bool fechaVigenciaFieldSpecified;
        
        private mensajeServicio[] mensajeServicioListField;
        
        private bool transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoPuntoVenta {
            get {
                return this.codigoPuntoVentaField;
            }
            set {
                this.codigoPuntoVentaField = value;
                this.RaisePropertyChanged("codigoPuntoVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified {
            get {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set {
                this.codigoPuntoVentaFieldSpecified = value;
                this.RaisePropertyChanged("codigoPuntoVentaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
                this.RaisePropertyChanged("codigoSucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSucursalSpecified {
            get {
                return this.codigoSucursalFieldSpecified;
            }
            set {
                this.codigoSucursalFieldSpecified = value;
                this.RaisePropertyChanged("codigoSucursalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaVigencia {
            get {
                return this.fechaVigenciaField;
            }
            set {
                this.fechaVigenciaField = value;
                this.RaisePropertyChanged("fechaVigencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVigenciaSpecified {
            get {
                return this.fechaVigenciaFieldSpecified;
            }
            set {
                this.fechaVigenciaFieldSpecified = value;
                this.RaisePropertyChanged("fechaVigenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajeServicioList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public mensajeServicio[] mensajeServicioList {
            get {
                return this.mensajeServicioListField;
            }
            set {
                this.mensajeServicioListField = value;
                this.RaisePropertyChanged("mensajeServicioList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaCufdMasivo : modelDto {
        
        private respuestaListaRegistroCufdSoapDto[] listaRespuestasCufdField;
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaRespuestasCufd", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public respuestaListaRegistroCufdSoapDto[] listaRespuestasCufd {
            get {
                return this.listaRespuestasCufdField;
            }
            set {
                this.listaRespuestasCufdField = value;
                this.RaisePropertyChanged("listaRespuestasCufd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public mensajeServicio[] mensajesList {
            get {
                return this.mensajesListField;
            }
            set {
                this.mensajesListField = value;
                this.RaisePropertyChanged("mensajesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified {
            get {
                return this.transaccionFieldSpecified;
            }
            set {
                this.transaccionFieldSpecified = value;
                this.RaisePropertyChanged("transaccionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaCuis : modelDto {
        
        private string codigoField;
        
        private System.DateTime fechaVigenciaField;
        
        private bool fechaVigenciaFieldSpecified;
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaVigencia {
            get {
                return this.fechaVigenciaField;
            }
            set {
                this.fechaVigenciaField = value;
                this.RaisePropertyChanged("fechaVigencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVigenciaSpecified {
            get {
                return this.fechaVigenciaFieldSpecified;
            }
            set {
                this.fechaVigenciaFieldSpecified = value;
                this.RaisePropertyChanged("fechaVigenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public mensajeServicio[] mensajesList {
            get {
                return this.mensajesListField;
            }
            set {
                this.mensajesListField = value;
                this.RaisePropertyChanged("mensajesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified {
            get {
                return this.transaccionFieldSpecified;
            }
            set {
                this.transaccionFieldSpecified = value;
                this.RaisePropertyChanged("transaccionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaCufd : modelDto {
        
        private string codigoField;
        
        private string codigoControlField;
        
        private string direccionField;
        
        private System.DateTime fechaVigenciaField;
        
        private bool fechaVigenciaFieldSpecified;
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoControl {
            get {
                return this.codigoControlField;
            }
            set {
                this.codigoControlField = value;
                this.RaisePropertyChanged("codigoControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaVigencia {
            get {
                return this.fechaVigenciaField;
            }
            set {
                this.fechaVigenciaField = value;
                this.RaisePropertyChanged("fechaVigencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVigenciaSpecified {
            get {
                return this.fechaVigenciaFieldSpecified;
            }
            set {
                this.fechaVigenciaFieldSpecified = value;
                this.RaisePropertyChanged("fechaVigenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public mensajeServicio[] mensajesList {
            get {
                return this.mensajesListField;
            }
            set {
                this.mensajesListField = value;
                this.RaisePropertyChanged("mensajesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified {
            get {
                return this.transaccionFieldSpecified;
            }
            set {
                this.transaccionFieldSpecified = value;
                this.RaisePropertyChanged("transaccionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaCuisMasivo : modelDto {
        
        private respuestaListaRegistroCuisSoapDto[] listaRespuestasCuisField;
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaRespuestasCuis", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public respuestaListaRegistroCuisSoapDto[] listaRespuestasCuis {
            get {
                return this.listaRespuestasCuisField;
            }
            set {
                this.listaRespuestasCuisField = value;
                this.RaisePropertyChanged("listaRespuestasCuis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public mensajeServicio[] mensajesList {
            get {
                return this.mensajesListField;
            }
            set {
                this.mensajesListField = value;
                this.RaisePropertyChanged("mensajesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified {
            get {
                return this.transaccionFieldSpecified;
            }
            set {
                this.transaccionFieldSpecified = value;
                this.RaisePropertyChanged("transaccionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaNotificaRevocado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaVerificarNit))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaConfiguracion : modelDto {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList {
            get {
                return this.mensajesListField;
            }
            set {
                this.mensajesListField = value;
                this.RaisePropertyChanged("mensajesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified {
            get {
                return this.transaccionFieldSpecified;
            }
            set {
                this.transaccionFieldSpecified = value;
                this.RaisePropertyChanged("transaccionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaNotificaRevocado : respuestaConfiguracion {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaVerificarNit : respuestaConfiguracion {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacion", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacion {
        
        public verificarComunicacion() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FacturacionCodigos.respuestaComunicacion RespuestaComunicacion;
        
        public verificarComunicacionResponse() {
        }
        
        public verificarComunicacionResponse(WindowsFormsApp1.FacturacionCodigos.respuestaComunicacion RespuestaComunicacion) {
            this.RespuestaComunicacion = RespuestaComunicacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarNit", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarNit {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FacturacionCodigos.solicitudVerificarNit SolicitudVerificarNit;
        
        public verificarNit() {
        }
        
        public verificarNit(WindowsFormsApp1.FacturacionCodigos.solicitudVerificarNit SolicitudVerificarNit) {
            this.SolicitudVerificarNit = SolicitudVerificarNit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarNitResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarNitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FacturacionCodigos.respuestaVerificarNit RespuestaVerificarNit;
        
        public verificarNitResponse() {
        }
        
        public verificarNitResponse(WindowsFormsApp1.FacturacionCodigos.respuestaVerificarNit RespuestaVerificarNit) {
            this.RespuestaVerificarNit = RespuestaVerificarNit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuisMasivo", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cuisMasivo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FacturacionCodigos.solicitudCuisMasivoSistemas SolicitudCuisMasivoSistemas;
        
        public cuisMasivo() {
        }
        
        public cuisMasivo(WindowsFormsApp1.FacturacionCodigos.solicitudCuisMasivoSistemas SolicitudCuisMasivoSistemas) {
            this.SolicitudCuisMasivoSistemas = SolicitudCuisMasivoSistemas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuisMasivoResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cuisMasivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FacturacionCodigos.respuestaCuisMasivo RespuestaCuisMasivo;
        
        public cuisMasivoResponse() {
        }
        
        public cuisMasivoResponse(WindowsFormsApp1.FacturacionCodigos.respuestaCuisMasivo RespuestaCuisMasivo) {
            this.RespuestaCuisMasivo = RespuestaCuisMasivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cufd", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cufd {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FacturacionCodigos.solicitudCufd SolicitudCufd;
        
        public cufd() {
        }
        
        public cufd(WindowsFormsApp1.FacturacionCodigos.solicitudCufd SolicitudCufd) {
            this.SolicitudCufd = SolicitudCufd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cufdResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cufdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FacturacionCodigos.respuestaCufd RespuestaCufd;
        
        public cufdResponse() {
        }
        
        public cufdResponse(WindowsFormsApp1.FacturacionCodigos.respuestaCufd RespuestaCufd) {
            this.RespuestaCufd = RespuestaCufd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="notificaCertificadoRevocado", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class notificaCertificadoRevocado {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FacturacionCodigos.solicitudNotifcaRevocado SolicitudNotificaRevocado;
        
        public notificaCertificadoRevocado() {
        }
        
        public notificaCertificadoRevocado(WindowsFormsApp1.FacturacionCodigos.solicitudNotifcaRevocado SolicitudNotificaRevocado) {
            this.SolicitudNotificaRevocado = SolicitudNotificaRevocado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="notificaCertificadoRevocadoResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class notificaCertificadoRevocadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FacturacionCodigos.respuestaNotificaRevocado RespuestaNotificaRevocado;
        
        public notificaCertificadoRevocadoResponse() {
        }
        
        public notificaCertificadoRevocadoResponse(WindowsFormsApp1.FacturacionCodigos.respuestaNotificaRevocado RespuestaNotificaRevocado) {
            this.RespuestaNotificaRevocado = RespuestaNotificaRevocado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuis", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cuis {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FacturacionCodigos.solicitudCuis SolicitudCuis;
        
        public cuis() {
        }
        
        public cuis(WindowsFormsApp1.FacturacionCodigos.solicitudCuis SolicitudCuis) {
            this.SolicitudCuis = SolicitudCuis;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuisResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cuisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FacturacionCodigos.respuestaCuis RespuestaCuis;
        
        public cuisResponse() {
        }
        
        public cuisResponse(WindowsFormsApp1.FacturacionCodigos.respuestaCuis RespuestaCuis) {
            this.RespuestaCuis = RespuestaCuis;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cufdMasivo", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cufdMasivo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FacturacionCodigos.solicitudCufdMasivo SolicitudCufdMasivo;
        
        public cufdMasivo() {
        }
        
        public cufdMasivo(WindowsFormsApp1.FacturacionCodigos.solicitudCufdMasivo SolicitudCufdMasivo) {
            this.SolicitudCufdMasivo = SolicitudCufdMasivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cufdMasivoResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cufdMasivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.FacturacionCodigos.respuestaCufdMasivo RespuestaCufdMasivo;
        
        public cufdMasivoResponse() {
        }
        
        public cufdMasivoResponse(WindowsFormsApp1.FacturacionCodigos.respuestaCufdMasivo RespuestaCufdMasivo) {
            this.RespuestaCufdMasivo = RespuestaCufdMasivo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioFacturacionCodigosChannel : WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFacturacionCodigosClient : System.ServiceModel.ClientBase<WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos>, WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos {
        
        public ServicioFacturacionCodigosClient() {
        }
        
        public ServicioFacturacionCodigosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFacturacionCodigosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturacionCodigosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturacionCodigosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.FacturacionCodigos.verificarComunicacionResponse WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.verificarComunicacion(WindowsFormsApp1.FacturacionCodigos.verificarComunicacion request) {
            return base.Channel.verificarComunicacion(request);
        }
        
        public WindowsFormsApp1.FacturacionCodigos.respuestaComunicacion verificarComunicacion() {
            WindowsFormsApp1.FacturacionCodigos.verificarComunicacion inValue = new WindowsFormsApp1.FacturacionCodigos.verificarComunicacion();
            WindowsFormsApp1.FacturacionCodigos.verificarComunicacionResponse retVal = ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).verificarComunicacion(inValue);
            return retVal.RespuestaComunicacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.verificarComunicacionResponse> WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.verificarComunicacionAsync(WindowsFormsApp1.FacturacionCodigos.verificarComunicacion request) {
            return base.Channel.verificarComunicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.verificarComunicacionResponse> verificarComunicacionAsync() {
            WindowsFormsApp1.FacturacionCodigos.verificarComunicacion inValue = new WindowsFormsApp1.FacturacionCodigos.verificarComunicacion();
            return ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).verificarComunicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.FacturacionCodigos.verificarNitResponse WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.verificarNit(WindowsFormsApp1.FacturacionCodigos.verificarNit request) {
            return base.Channel.verificarNit(request);
        }
        
        public WindowsFormsApp1.FacturacionCodigos.respuestaVerificarNit verificarNit(WindowsFormsApp1.FacturacionCodigos.solicitudVerificarNit SolicitudVerificarNit) {
            WindowsFormsApp1.FacturacionCodigos.verificarNit inValue = new WindowsFormsApp1.FacturacionCodigos.verificarNit();
            inValue.SolicitudVerificarNit = SolicitudVerificarNit;
            WindowsFormsApp1.FacturacionCodigos.verificarNitResponse retVal = ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).verificarNit(inValue);
            return retVal.RespuestaVerificarNit;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.verificarNitResponse> WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.verificarNitAsync(WindowsFormsApp1.FacturacionCodigos.verificarNit request) {
            return base.Channel.verificarNitAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.verificarNitResponse> verificarNitAsync(WindowsFormsApp1.FacturacionCodigos.solicitudVerificarNit SolicitudVerificarNit) {
            WindowsFormsApp1.FacturacionCodigos.verificarNit inValue = new WindowsFormsApp1.FacturacionCodigos.verificarNit();
            inValue.SolicitudVerificarNit = SolicitudVerificarNit;
            return ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).verificarNitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.FacturacionCodigos.cuisMasivoResponse WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.cuisMasivo(WindowsFormsApp1.FacturacionCodigos.cuisMasivo request) {
            return base.Channel.cuisMasivo(request);
        }
        
        public WindowsFormsApp1.FacturacionCodigos.respuestaCuisMasivo cuisMasivo(WindowsFormsApp1.FacturacionCodigos.solicitudCuisMasivoSistemas SolicitudCuisMasivoSistemas) {
            WindowsFormsApp1.FacturacionCodigos.cuisMasivo inValue = new WindowsFormsApp1.FacturacionCodigos.cuisMasivo();
            inValue.SolicitudCuisMasivoSistemas = SolicitudCuisMasivoSistemas;
            WindowsFormsApp1.FacturacionCodigos.cuisMasivoResponse retVal = ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).cuisMasivo(inValue);
            return retVal.RespuestaCuisMasivo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.cuisMasivoResponse> WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.cuisMasivoAsync(WindowsFormsApp1.FacturacionCodigos.cuisMasivo request) {
            return base.Channel.cuisMasivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.cuisMasivoResponse> cuisMasivoAsync(WindowsFormsApp1.FacturacionCodigos.solicitudCuisMasivoSistemas SolicitudCuisMasivoSistemas) {
            WindowsFormsApp1.FacturacionCodigos.cuisMasivo inValue = new WindowsFormsApp1.FacturacionCodigos.cuisMasivo();
            inValue.SolicitudCuisMasivoSistemas = SolicitudCuisMasivoSistemas;
            return ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).cuisMasivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.FacturacionCodigos.cufdResponse WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.cufd(WindowsFormsApp1.FacturacionCodigos.cufd request) {
            return base.Channel.cufd(request);
        }
        
        public WindowsFormsApp1.FacturacionCodigos.respuestaCufd cufd(WindowsFormsApp1.FacturacionCodigos.solicitudCufd SolicitudCufd) {
            WindowsFormsApp1.FacturacionCodigos.cufd inValue = new WindowsFormsApp1.FacturacionCodigos.cufd();
            inValue.SolicitudCufd = SolicitudCufd;
            WindowsFormsApp1.FacturacionCodigos.cufdResponse retVal = ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).cufd(inValue);
            return retVal.RespuestaCufd;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.cufdResponse> WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.cufdAsync(WindowsFormsApp1.FacturacionCodigos.cufd request) {
            return base.Channel.cufdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.cufdResponse> cufdAsync(WindowsFormsApp1.FacturacionCodigos.solicitudCufd SolicitudCufd) {
            WindowsFormsApp1.FacturacionCodigos.cufd inValue = new WindowsFormsApp1.FacturacionCodigos.cufd();
            inValue.SolicitudCufd = SolicitudCufd;
            return ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).cufdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocadoResponse WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.notificaCertificadoRevocado(WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocado request) {
            return base.Channel.notificaCertificadoRevocado(request);
        }
        
        public WindowsFormsApp1.FacturacionCodigos.respuestaNotificaRevocado notificaCertificadoRevocado(WindowsFormsApp1.FacturacionCodigos.solicitudNotifcaRevocado SolicitudNotificaRevocado) {
            WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocado inValue = new WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocado();
            inValue.SolicitudNotificaRevocado = SolicitudNotificaRevocado;
            WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocadoResponse retVal = ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).notificaCertificadoRevocado(inValue);
            return retVal.RespuestaNotificaRevocado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocadoResponse> WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.notificaCertificadoRevocadoAsync(WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocado request) {
            return base.Channel.notificaCertificadoRevocadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocadoResponse> notificaCertificadoRevocadoAsync(WindowsFormsApp1.FacturacionCodigos.solicitudNotifcaRevocado SolicitudNotificaRevocado) {
            WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocado inValue = new WindowsFormsApp1.FacturacionCodigos.notificaCertificadoRevocado();
            inValue.SolicitudNotificaRevocado = SolicitudNotificaRevocado;
            return ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).notificaCertificadoRevocadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.FacturacionCodigos.cuisResponse WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.cuis(WindowsFormsApp1.FacturacionCodigos.cuis request) {
            return base.Channel.cuis(request);
        }
        
        public WindowsFormsApp1.FacturacionCodigos.respuestaCuis cuis(WindowsFormsApp1.FacturacionCodigos.solicitudCuis SolicitudCuis) {
            WindowsFormsApp1.FacturacionCodigos.cuis inValue = new WindowsFormsApp1.FacturacionCodigos.cuis();
            inValue.SolicitudCuis = SolicitudCuis;
            WindowsFormsApp1.FacturacionCodigos.cuisResponse retVal = ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).cuis(inValue);
            return retVal.RespuestaCuis;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.cuisResponse> WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.cuisAsync(WindowsFormsApp1.FacturacionCodigos.cuis request) {
            return base.Channel.cuisAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.cuisResponse> cuisAsync(WindowsFormsApp1.FacturacionCodigos.solicitudCuis SolicitudCuis) {
            WindowsFormsApp1.FacturacionCodigos.cuis inValue = new WindowsFormsApp1.FacturacionCodigos.cuis();
            inValue.SolicitudCuis = SolicitudCuis;
            return ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).cuisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.FacturacionCodigos.cufdMasivoResponse WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.cufdMasivo(WindowsFormsApp1.FacturacionCodigos.cufdMasivo request) {
            return base.Channel.cufdMasivo(request);
        }
        
        public WindowsFormsApp1.FacturacionCodigos.respuestaCufdMasivo cufdMasivo(WindowsFormsApp1.FacturacionCodigos.solicitudCufdMasivo SolicitudCufdMasivo) {
            WindowsFormsApp1.FacturacionCodigos.cufdMasivo inValue = new WindowsFormsApp1.FacturacionCodigos.cufdMasivo();
            inValue.SolicitudCufdMasivo = SolicitudCufdMasivo;
            WindowsFormsApp1.FacturacionCodigos.cufdMasivoResponse retVal = ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).cufdMasivo(inValue);
            return retVal.RespuestaCufdMasivo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.cufdMasivoResponse> WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos.cufdMasivoAsync(WindowsFormsApp1.FacturacionCodigos.cufdMasivo request) {
            return base.Channel.cufdMasivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.FacturacionCodigos.cufdMasivoResponse> cufdMasivoAsync(WindowsFormsApp1.FacturacionCodigos.solicitudCufdMasivo SolicitudCufdMasivo) {
            WindowsFormsApp1.FacturacionCodigos.cufdMasivo inValue = new WindowsFormsApp1.FacturacionCodigos.cufdMasivo();
            inValue.SolicitudCufdMasivo = SolicitudCufdMasivo;
            return ((WindowsFormsApp1.FacturacionCodigos.ServicioFacturacionCodigos)(this)).cufdMasivoAsync(inValue);
        }
    }
}
